import { persistedD1Blob } from "@/modules/db/persisted-blob";
import { d1Changes } from "@/modules/platform/types";
import type { EncryptedValue } from "@/modules/security/keyring";

export type ConversationReminderStatus = "PENDING" | "CLAIMED" | "RETRYABLE" | "UNCERTAIN";
export interface BoundConversationMessage { id: string; connectionId: string; providerUserId: string; privateChatId: string; claimMarker: string; receivedAt: number; }
export interface ActiveClarification { id: string; sourceInboundId: string; encryptedTitle: EncryptedValue; titleKeyVersion: number; localDate: string | null; expiresAt: number; }
export interface CreateClarificationMutation { clarificationId: string; message: BoundConversationMessage; chatIdentityId: string; encryptedTitle: EncryptedValue; titleKeyVersion: number; localDate?: string; expiresAt: number; now: number; }
export interface ResolveClarificationMutation { message: BoundConversationMessage; clarification: ActiveClarification; now: number; }
export interface OwnedRangeQuery { userId: string; from: number; to: number; limit: number; }
export interface OwnedReminderRow { id: string; titleCiphertext: unknown; titleIv: unknown; titleKeyVersion: number; scheduledAt: number; status: ConversationReminderStatus; }

export class D1ConversationStore {
  constructor(private readonly database: D1Database) {}
  async createClarification(input: CreateClarificationMutation): Promise<"COMMITTED"|"SUPERSEDED"> {
    const r=await this.database.prepare(`INSERT OR IGNORE INTO conversation_clarifications (id,chat_identity_id,source_inbound_id,title_ciphertext,title_iv,title_key_version,local_date,state,expires_at,created_at,updated_at) SELECT ?,?,?,?,?,?,?,'PENDING',?,?,? WHERE EXISTS(SELECT 1 FROM chat_identities c JOIN inbound_updates i ON i.connection_id=c.connection_id AND i.provider_user_id=c.provider_user_id AND i.private_chat_id=c.private_chat_id WHERE c.id=? AND i.id=? AND i.connection_id=? AND i.provider_user_id=? AND i.private_chat_id=? AND i.state='PROCESSING' AND i.transition_marker=?)`).bind(input.clarificationId,input.chatIdentityId,input.message.id,input.encryptedTitle.ciphertext,input.encryptedTitle.iv,input.titleKeyVersion,input.localDate??null,input.expiresAt,input.now,input.now,input.chatIdentityId,input.message.id,input.message.connectionId,input.message.providerUserId,input.message.privateChatId,input.message.claimMarker).run(); return d1Changes(r)===1?"COMMITTED":"SUPERSEDED";
  }
  async findActiveClarification(message:BoundConversationMessage,chatIdentityId:string):Promise<ActiveClarification|null> { const r=await this.database.prepare(`SELECT id,source_inbound_id,title_ciphertext,title_iv,title_key_version,local_date,expires_at FROM conversation_clarifications WHERE chat_identity_id=? AND state='PENDING' AND expires_at>=? AND EXISTS(SELECT 1 FROM chat_identities c JOIN inbound_updates i ON i.connection_id=c.connection_id AND i.provider_user_id=c.provider_user_id AND i.private_chat_id=c.private_chat_id WHERE c.id=conversation_clarifications.chat_identity_id AND i.id=? AND i.connection_id=? AND i.provider_user_id=? AND i.private_chat_id=? AND i.state='PROCESSING' AND i.transition_marker=?) LIMIT 1`).bind(chatIdentityId,message.receivedAt,message.id,message.connectionId,message.providerUserId,message.privateChatId,message.claimMarker).first<any>(); return r?{id:r.id,sourceInboundId:r.source_inbound_id,encryptedTitle:{ciphertext:persistedD1Blob(r.title_ciphertext),iv:persistedD1Blob(r.title_iv)},titleKeyVersion:r.title_key_version,localDate:r.local_date,expiresAt:r.expires_at}:null; }
  async resolveClarification(input:ResolveClarificationMutation):Promise<"COMMITTED"|"ALREADY_RESOLVED"|"EXPIRED"|"SUPERSEDED"> { const r=await this.database.prepare(`UPDATE conversation_clarifications SET state='RESOLVED',resolution_inbound_id=?,updated_at=? WHERE id=? AND state='PENDING' AND expires_at>? `).bind(input.message.id,input.now,input.clarification.id,input.now).run(); if(d1Changes(r))return"COMMITTED";const row=await this.database.prepare("SELECT state,expires_at FROM conversation_clarifications WHERE id=?").bind(input.clarification.id).first<any>();if(row?.state==="RESOLVED")return"ALREADY_RESOLVED";if(row?.state==="PENDING"&&row.expires_at<=input.now){await this.database.prepare("UPDATE conversation_clarifications SET state='EXPIRED',updated_at=? WHERE id=? AND state='PENDING'").bind(input.now,input.clarification.id).run();return"EXPIRED";}return"SUPERSEDED"; }
  async cancelClarification(input:ResolveClarificationMutation):Promise<"COMMITTED"|"SUPERSEDED">{const r=await this.database.prepare("UPDATE conversation_clarifications SET state='CANCELLED',resolution_inbound_id=?,updated_at=? WHERE id=? AND state='PENDING'").bind(input.message.id,input.now,input.clarification.id).run();if(d1Changes(r))return"COMMITTED";const row=await this.database.prepare("SELECT state,resolution_inbound_id FROM conversation_clarifications WHERE id=?").bind(input.clarification.id).first<any>();return row?.state==="CANCELLED"&&row.resolution_inbound_id===input.message.id?"COMMITTED":"SUPERSEDED";}
  async listActiveScheduled(input:OwnedRangeQuery):Promise<OwnedReminderRow[]>{const r=await this.database.prepare(`SELECT r.id,r.title_ciphertext,r.title_iv,r.title_key_version,r.scheduled_at,r.status FROM reminders r JOIN workspaces w ON w.id=r.workspace_id JOIN memberships m ON m.workspace_id=w.id AND m.user_id=w.owner_user_id WHERE w.kind='PERSONAL' AND w.owner_user_id=? AND m.role='OWNER' AND r.status IN ('PENDING','CLAIMED','RETRYABLE','UNCERTAIN') AND r.scheduled_at>=? AND r.scheduled_at<? ORDER BY r.scheduled_at,r.id LIMIT ?`).bind(input.userId,input.from,input.to,input.limit).all<any>();return r.results.map(x=>({id:x.id,titleCiphertext:x.title_ciphertext,titleIv:x.title_iv,titleKeyVersion:x.title_key_version,scheduledAt:x.scheduled_at,status:x.status}));}
