// Canonical production AI bindings and required secret names are generated by
// Wrangler. Only unconfigured, rejected legacy inputs remain optional here.
interface Env {
  OPENROUTER_FREE_MODEL?: string;
  OPENROUTER_FALLBACK_MODELS?: string;
}
