"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Check, ChevronLeft, ChevronRight, CircleCheck, RotateCcw, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { ActionDecisionResponseSchema, ActionsResponseSchema, type PublicPendingAction } from "@/contracts/api/actions";
import { RemindersResponseSchema, type PublicReminder } from "@/contracts/api/reminders";
import { SessionResponseSchema, type SessionUser } from "@/contracts/api/session";
import { AmbiguousMutationError, ApiResponseError, apiRequest } from "@/lib/client-api";
import { AppShell } from "@/ui/shell/AppShell";
import { isActiveReminder } from "@/features/today/projection";
import styles from "./CoreScreenExperience.module.css";
import { ReminderSeriesPanel } from "./ReminderSeriesPanel";

export type CoreScreen = "calendar" | "inbox" | "reminders";
type Resource<T> = { value: T | null; error: string | null };
const empty = <T,>(): Resource<T> => ({ value: null, error: null });
const status = (value: PublicReminder["status"]) => ({ PENDING: "Sắp tới", CLAIMED: "Đang chuẩn bị", RETRYABLE: "Sắp thử lại", SENT: "Đã nhắc", FAILED: "Chưa gửi được", UNCERTAIN: "Cần kiểm tra", CANCELLED: "Đã huỷ" })[value];
const clock = (value: number) => new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(value);
const dateKey = (value: number) => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh", year: "numeric", month: "2-digit", day: "2-digit" }).format(value);
const dateLabel = (value: number) => new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", day: "numeric", month: "long", weekday: "long" }).format(value);
function humanDate(value: number) { const now = Date.now(); return dateKey(value) === dateKey(now) ? `Hôm nay · ${clock(value)}` : dateKey(value) === dateKey(now + 86_400_000) ? `Ngày mai · ${clock(value)}` : `${new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", day: "numeric", month: "long" }).format(value)} · ${clock(value)}`; }
function LocalError({ message, retry }: { message: string; retry: () => void }) { return <div className={styles.error} role="alert"><span>{message}</span><button type="button" onClick={retry}><RotateCcw size={16} aria-hidden="true" />Thử lại</button></div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className={styles.empty}><h2>{title}</h2><p>{text}</p><a href="/app/today">Tạo lời nhắc mới →</a></div>; }
function Loading() { return <div className={styles.loading} aria-label="Đang tải"><span /><span /><span /></div>; }

export function CoreScreenExperience({ screen }: { screen: CoreScreen }) {
  const { replace } = useRouter(); const epoch = useRef(0);
  const [user, setUser] = useState<SessionUser | null>(null); const [sessionError, setSessionError] = useState<string | null>(null);
  const [reminders, setReminders] = useState<Resource<PublicReminder[]>>(empty()); const [actions, setActions] = useState<Resource<PublicPendingAction[]>>(empty());
  const [notice, setNotice] = useState<string | null>(null); const [busyId, setBusyId] = useState<string | null>(null);
  const path = `/app/${screen}`;
  const redirect = useCallback(() => { epoch.current += 1; setUser(null); replace("/login"); }, [replace]);
  const loadReminders = useCallback(async (current: number) => { setReminders((old) => ({ ...old, error: null })); try { const data = await apiRequest<unknown>("/api/reminders", { authenticated: true, onUnauthorized: redirect }); const value = RemindersResponseSchema.parse({ data }).data.reminders; if (epoch.current === current) setReminders({ value, error: null }); } catch (error) { if (epoch.current === current) setReminders((old) => ({ ...old, error: error instanceof ApiResponseError ? error.message : "Chưa thể tải lời nhắc." })); } }, [redirect]);
  const loadActions = useCallback(async (current: number) => { setActions((old) => ({ ...old, error: null })); try { const data = await apiRequest<unknown>("/api/actions", { authenticated: true, onUnauthorized: redirect }); const value = ActionsResponseSchema.parse({ data }).data.actions; if (epoch.current === current) setActions({ value, error: null }); } catch (error) { if (epoch.current === current) setActions((old) => ({ ...old, error: error instanceof ApiResponseError ? error.message : "Chưa thể tải đề xuất." })); } }, [redirect]);
  useEffect(() => { const current = epoch.current + 1; epoch.current = current; void (async () => { try { const data = await apiRequest<unknown>("/api/session", { authenticated: true, onUnauthorized: redirect }); const next = SessionResponseSchema.parse({ data }).data.user; if (epoch.current !== current) return; setUser(next); if (screen === "inbox") void loadActions(current); else void loadReminders(current); } catch (error) { if (epoch.current === current) setSessionError(error instanceof ApiResponseError ? error.message : "Chưa thể mở Calenote."); } })(); }, [loadActions, loadReminders, redirect, screen]);
  const decide = async (candidate: PublicPendingAction, decision: "approve" | "reject") => { const current = epoch.current; setBusyId(candidate.id); try { const data = await apiRequest<unknown>(`/api/actions/${candidate.id}/${decision}`, { method: "POST", body: {}, authenticated: true, onUnauthorized: redirect }); ActionDecisionResponseSchema.parse({ data }); if (epoch.current === current) { setActions((old) => ({ ...old, value: old.value?.filter((value) => value.id !== candidate.id) ?? null })); setNotice(decision === "approve" ? "Đề xuất đã được duyệt." : "Đề xuất đã được bỏ qua."); } } catch (error) { if (epoch.current === current) setNotice(error instanceof AmbiguousMutationError ? "Kết quả chưa xác định. Hãy làm mới trước khi thử lại." : "Chưa thể xử lý đề xuất."); } finally { if (epoch.current === current) setBusyId(null); } };
  const cancel = async (reminder: PublicReminder) => { const current = epoch.current; setBusyId(reminder.publicId); try { await apiRequest<unknown>(`/api/reminders/${reminder.publicId}/cancel`, { method: "POST", body: {}, authenticated: true, onUnauthorized: redirect }); if (epoch.current === current) { setReminders((old) => ({ ...old, value: old.value?.map((value) => value.publicId === reminder.publicId ? { ...value, status: "CANCELLED" } : value) ?? null })); setNotice("Lời nhắc đã được huỷ."); } } catch { if (epoch.current === current) setNotice("Chưa thể huỷ lời nhắc."); } finally { if (epoch.current === current) setBusyId(null); } };
  if (sessionError) return <main className={styles.entry}><LocalError message={sessionError} retry={() => location.reload()} /></main>;
  if (!user) return <main className={styles.entry}><Loading /></main>;
  return <AppShell user={user} activePath={path}><main className={styles.page}>{notice && <p className={styles.notice} role="status"><CircleCheck size={17} aria-hidden="true" />{notice}</p>}{screen === "calendar" ? <Calendar reminders={reminders} retry={() => void loadReminders(epoch.current)} /> : screen === "inbox" ? <Inbox actions={actions} busyId={busyId} decide={decide} retry={() => void loadActions(epoch.current)} /> : <Reminders reminders={reminders} busyId={busyId} cancel={cancel} retry={() => void loadReminders(epoch.current)} />}{screen !== "calendar" && <ReminderSeriesPanel onUnauthorized={redirect} onChanged={() => void loadReminders(epoch.current)} />}</main></AppShell>;
}

function Calendar({ reminders, retry }: { reminders: Resource<PublicReminder[]>; retry: () => void }) { const [month, setMonth] = useState(() => new Date()); const [selected, setSelected] = useState(() => dateKey(Date.now())); const [detail, setDetail] = useState<PublicReminder | null>(null); const first = new Date(month.getFullYear(), month.getMonth(), 1); const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const offset = (first.getDay() + 6) % 7; const title = new Intl.DateTimeFormat("vi-VN", { month: "long", year: "numeric" }).format(month); const selectEpoch = (day: number) => Date.UTC(month.getFullYear(), month.getMonth(), day, 5); const selectedItems = reminders.value?.filter((item) => dateKey(item.scheduledAt) === selected).sort((a, b) => a.scheduledAt - b.scheduledAt) ?? [];
  return <><header className={styles.header}><p>Lịch cá nhân</p><h1>Lịch</h1><span>Những lời nhắc bạn đã tạo cho mình.</span></header><section className={styles.calendar}><div className={styles.period}><button type="button" aria-label="Tháng trước" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1))}><ChevronLeft aria-hidden="true" /></button><h2>{title}</h2><button type="button" aria-label="Tháng sau" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1))}><ChevronRight aria-hidden="true" /></button><button type="button" onClick={() => { setMonth(new Date()); setSelected(dateKey(Date.now())); }}>Hôm nay</button></div><div className={styles.week} aria-label="Các ngày trong tuần">{"T2 T3 T4 T5 T6 T7 CN".split(" ").map((day) => <span key={day}>{day}</span>)}</div><div className={styles.month}>{Array.from({ length: offset }, (_, index) => <span key={`empty-${index}`} />)}{Array.from({ length: days }, (_, index) => { const day = index + 1; const key = dateKey(selectEpoch(day)); const count = reminders.value?.filter((item) => dateKey(item.scheduledAt) === key).length ?? 0; return <button key={day} type="button" aria-pressed={selected === key} className={selected === key ? styles.selectedDay : undefined} onClick={() => setSelected(key)}><span>{day}</span>{count > 0 && <i aria-label={`${count} lời nhắc`} />}</button>; })}</div></section><section className={styles.agenda} aria-labelledby="agenda-title"><h2 id="agenda-title">{dateLabel(Date.parse(`${selected}T05:00:00Z`))}</h2>{reminders.error ? <LocalError message={reminders.error} retry={retry} /> : reminders.value === null ? <Loading /> : selectedItems.length === 0 ? <Empty title="Ngày này đang khá thoáng." text="Chưa có lời nhắc nào." /> : selectedItems.map((item) => <button className={styles.agendaItem} key={item.publicId} type="button" onClick={() => setDetail(item)}><time>{clock(item.scheduledAt)}</time><span><strong>{item.title}</strong><small>{status(item.status)}</small></span></button>)}</section>{detail && <section className={styles.detail} aria-label="Chi tiết lời nhắc"><button type="button" aria-label="Đóng chi tiết" onClick={() => setDetail(null)}><X aria-hidden="true" /></button><p>{humanDate(detail.scheduledAt)}</p><h2>{detail.title}</h2><span>{status(detail.status)}</span></section>}</> }
function Inbox({ actions, busyId, decide, retry }: { actions: Resource<PublicPendingAction[]>; busyId: string | null; decide: (candidate: PublicPendingAction, decision: "approve" | "reject") => void; retry: () => void }) { return <><header className={styles.header}><p>Không gian quyết định</p><h1>Hộp thư</h1><span>Những việc đang chờ bạn.</span></header><section aria-labelledby="pending-title"><h2 className={styles.sectionTitle} id="pending-title">Cần xác nhận</h2>{actions.error ? <LocalError message={actions.error} retry={retry} /> : actions.value === null ? <Loading /> : actions.value.length === 0 ? <Empty title="Không có gì đang chờ bạn." text="Khi Calenote cần bạn xác nhận, nội dung sẽ xuất hiện ở đây." /> : <div className={styles.cards}>{actions.value.map((item) => <article className={styles.proposal} key={item.id}><span>Calenote đề xuất</span><h2>{item.title}</h2><p>{humanDate(item.scheduledAt)} · Chưa tạo lời nhắc</p><div><button type="button" aria-label={`Đồng ý ${item.title}`} disabled={busyId === item.id} onClick={() => decide(item, "approve")}><Check size={17} aria-hidden="true" />Đồng ý</button><button type="button" aria-label={`Bỏ qua ${item.title}`} disabled={busyId === item.id} onClick={() => decide(item, "reject")}>Bỏ qua</button></div></article>)}</div>}</section></> }
function Reminders({ reminders, busyId, cancel, retry }: { reminders: Resource<PublicReminder[]>; busyId: string | null; cancel: (reminder: PublicReminder) => void; retry: () => void }) { const [filter, setFilter] = useState<"upcoming" | "all">("upcoming"); const visible = (reminders.value ?? []).filter((item) => filter === "all" || isActiveReminder(item)).sort((a, b) => a.scheduledAt - b.scheduledAt); return <><header className={styles.header}><p>Không gian nhắc hẹn</p><h1>Lời nhắc</h1><span>Những điều bạn đã nhờ Calenote ghi nhớ.</span></header><div className={styles.tabs} role="tablist" aria-label="Lọc lời nhắc"><button role="tab" aria-selected={filter === "upcoming"} type="button" onClick={() => setFilter("upcoming")}>Đang chờ</button><button role="tab" aria-selected={filter === "all"} type="button" onClick={() => setFilter("all")}>Tất cả</button></div>{reminders.error ? <LocalError message={reminders.error} retry={retry} /> : reminders.value === null ? <Loading /> : visible.length === 0 ? <Empty title={filter === "upcoming" ? "Không có lời nhắc đang chờ gửi." : "Chưa có lời nhắc nào."} text={filter === "upcoming" ? "Chọn Tất cả để xem lịch sử, hoặc tạo một lời nhắc mới." : "Bắt đầu với một việc bạn muốn Calenote ghi nhớ."} /> : <div className={styles.reminderList}>{visible.map((item) => <article className={styles.reminder} key={item.publicId}><time>{humanDate(item.scheduledAt)}</time><div><h2>{item.title}</h2><p>{status(item.status)}</p></div>{["PENDING", "CLAIMED", "RETRYABLE"].includes(item.status) && <button type="button" aria-label={`Huỷ ${item.title}`} disabled={busyId === item.publicId} onClick={() => cancel(item)}>Huỷ</button>}</article>)}</div>}</> }
