"use client";
import { useCallback, useEffect, useState } from "react";
import { CircleAlert, Link2, RefreshCw, Settings2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { ConnectionsResponseSchema, type PublicConnection } from "@/contracts/api/connections";
import { ActivityResponseSchema, type PublicActivity } from "@/contracts/api/activity";
import { PreferencesResponseSchema, type PublicPreferences } from "@/contracts/api/preferences";
import { SessionResponseSchema, type SessionUser } from "@/contracts/api/session";
import { apiRequest } from "@/lib/client-api";
import { AppShell } from "@/ui/shell/AppShell";
import styles from "./FinalScreenExperience.module.css";
export type FinalScreen = "connections" | "activity" | "settings";
const status=(s:PublicConnection["state"])=>s==="ACTIVE_BOUND"?"Đã kết nối":s==="WEBHOOK_FAILED"||s==="SUSPENDED"?"Cần kiểm tra":"Chưa kết nối";
export function FinalScreenExperience({screen}:{screen:FinalScreen}) { const {replace}=useRouter(); const [user,setUser]=useState<SessionUser|null>(null); const [error,setError]=useState(false); const [connections,setConnections]=useState<PublicConnection[]|null>(null); const [activities,setActivities]=useState<PublicActivity[]|null>(null); const [preferences,setPreferences]=useState<PublicPreferences|null>(null); const [notice,setNotice]=useState<string|null>(null); const load=useCallback(async()=>{setError(false);try { const session=SessionResponseSchema.parse({data:await apiRequest<unknown>("/api/session",{authenticated:true,onUnauthorized:()=>replace("/login")})}).data.user; setUser(session); if(screen==="connections")setConnections(ConnectionsResponseSchema.parse({data:await apiRequest<unknown>("/api/connections",{authenticated:true,onUnauthorized:()=>replace("/login")})}).data.connections); if(screen==="activity")setActivities(ActivityResponseSchema.parse({data:await apiRequest<unknown>("/api/activity",{authenticated:true,onUnauthorized:()=>replace("/login")})}).data.activities); if(screen==="settings")setPreferences(PreferencesResponseSchema.parse({data:await apiRequest<unknown>("/api/preferences",{authenticated:true,onUnauthorized:()=>replace("/login")})}).data.preferences);}catch{setError(true)}},[replace,screen]);useEffect(()=>{queueMicrotask(()=>{void load();});},[load]);async function save(patch:Partial<PublicPreferences>){try{setPreferences(PreferencesResponseSchema.parse({data:await apiRequest<unknown>("/api/preferences",{method:"PATCH" as never,body:patch,authenticated:true,onUnauthorized:()=>replace("/login")})}).data.preferences);setNotice("Cài đặt đã được lưu.")}catch{setNotice("Chưa thể lưu cài đặt. Vui lòng thử lại.")}}if(!user)return <main className={styles.entry}><section><h1>{error?"Chưa mở được Calenote":"Đang mở Calenote"}</h1>{error&&<button onClick={()=>void load()}>Thử lại</button>}</section></main>;return <AppShell user={user} activePath={`/app/${screen}`}><main className={styles.page}><header><p>{screen==="connections"?"Kênh hỗ trợ":screen==="activity"?"Dòng thời gian":"Không gian cá nhân"}</p><h1>{screen==="connections"?"Kết nối":screen==="activity"?"Hoạt động":"Cài đặt"}</h1><span>{screen==="connections"?"Kết nối những nơi bạn muốn Calenote hỗ trợ.":screen==="activity"?"Những thay đổi quan trọng gần đây.":"Điều chỉnh cách Calenote đồng hành cùng bạn."}</span></header>{error?<Error retry={load}/>:screen==="connections"?<Connections value={connections}/>:screen==="activity"?<ActivityFeed value={activities}/>:<Settings user={user} value={preferences} save={save} notice={notice}/>}</main></AppShell> }
function ActivityFeed({value}:{value:PublicActivity[]|null}){if(value===null)return <Loading/>;if(!value.length)return <Empty title="Chưa có hoạt động nào." text="Những thay đổi quan trọng sẽ xuất hiện ở đây."/>;const copy={REMINDER_CREATED:"Đã tạo lời nhắc",REMINDER_CANCELLED:"Đã huỷ lời nhắc",CONNECT_CODE_ROTATED:"Đã làm mới mã kết nối",CHAT_BOUND:"Đã kết nối kênh"} as const;return <ol className={styles.cards}>{value.map((x,i)=><li className={styles.card} key={`${x.createdAt}-${i}`}><div><h2>{copy[x.action]}</h2><time dateTime={new Date(x.createdAt).toISOString()}>{new Intl.DateTimeFormat("vi-VN",{dateStyle:"medium",timeStyle:"short"}).format(x.createdAt)}</time></div></li>)}</ol>}
function Connections({value}:{value:PublicConnection[]|null}){if(value===null)return <Loading/>;if(!value.length)return <Empty title="Chưa có kết nối nào." text="Telegram và Zalo sẽ xuất hiện ở đây sau khi được thiết lập."/>;return <div className={styles.cards}>{value.map(x=><article className={styles.card} key={x.publicId}><Link2 aria-hidden="true"/><div><h2>{x.provider==="telegram"?"Telegram":"Zalo"}</h2><p>{x.displayName}</p><strong>{status(x.state)}</strong>{x.state==="WEBHOOK_FAILED"&&<p>Kết nối cần được xác minh lại.</p>}</div></article>)}</div>}
function Settings({user,value,save,notice}:{user:SessionUser;value:PublicPreferences|null;save:(p:Partial<PublicPreferences>)=>Promise<void>;notice:string|null}){if(!value)return <Loading/>;return <div className={styles.cards}><section className={styles.card}><div><h2>Hồ sơ</h2><label>Tên hiển thị<input readOnly value={user.displayName}/></label><label>Email<input readOnly value={user.email}/></label></div></section><section className={styles.card}><div><h2>Cá nhân hoá</h2><label>Cách xưng hô<select value={value.addressStyle} onChange={e=>void save({addressStyle:e.target.value as PublicPreferences["addressStyle"]})}><option value="ban">Bạn / mình</option><option value="anh_chi">Anh / chị</option><option value="ong_tui">Ông / tui</option><option value="minh">Mình</option></select></label><label>Giọng điệu<select value={value.tone} onChange={e=>void save({tone:e.target.value as PublicPreferences["tone"]})}><option value="concise">Ngắn gọn</option><option value="friendly">Thân thiện</option><option value="professional">Chuyên nghiệp</option><option value="playful">Vui vẻ</option></select></label></div></section><section className={styles.card}><Settings2 aria-hidden="true"/><div><h2>Hỗ trợ thông minh</h2><p>Calenote ưu tiên cách xử lý miễn phí; khi được cấu hình, có thể dùng lựa chọn chi phí rất thấp. Bạn luôn xác nhận đề xuất trước khi tạo lời nhắc.</p></div></section><section className={styles.card}><div><h2>Quyền riêng tư</h2><p>Thông tin đăng nhập không được hiển thị sau khi lưu. Nội dung nhạy cảm không được gửi vào Hỗ trợ thông minh tùy chọn.</p></div></section>{notice&&<p role="status">{notice}</p>}</div>}
function Loading(){return <div className={styles.loading} aria-label="Đang tải"><span/><span/><span/></div>}function Empty({title,text}:{title:string;text:string}){return <section className={styles.empty}><h2>{title}</h2><p>{text}</p></section>}function Error({retry}:{retry:()=>void}){return <section className={styles.error} role="alert"><CircleAlert aria-hidden="true"/><p>Chưa tải được dữ liệu.</p><button onClick={()=>void retry()}><RefreshCw aria-hidden="true"/>Thử lại</button></section>}
